
  CREATE TABLE "USER_NAME"."DEVICES_DATA" 
   (	"ID" NUMBER(*,0), 
	"BATTERYPOWER" NUMBER(*,0), 
	"BLUE" NUMBER(*,0), 
	"CLOCKSPEED" FLOAT(63), 
	"DUALSIM" NUMBER(*,0), 
	"FC" FLOAT(63), 
	"FOURG" NUMBER(*,0), 
	"INTMEMORY" NUMBER(*,0), 
	"MDEP" FLOAT(63), 
	"MOBILEWT" FLOAT(63), 
	"NCORES" NUMBER(*,0), 
	"PC" FLOAT(63), 
	"PXHEIGHT" NUMBER(*,0), 
	"PXWIDTH" NUMBER(*,0), 
	"RAM" NUMBER(*,0), 
	"SCH" NUMBER(*,0), 
	"SCW" NUMBER(*,0), 
	"TALKTIME" NUMBER(*,0), 
	"THREEG" NUMBER(*,0), 
	"TOUCHSCREEN" NUMBER(*,0), 
	"WIFI" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  
  CREATE TABLE "USER_NAME"."PRICES_DATA" 
   (	"ID" NUMBER(*,0), 
	"DEVICE_ID" NUMBER(*,0), 
	"PREDICTION" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("DEVICE_ID")
	  REFERENCES "MARTINA"."DEVICES_DATA" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;



